import { Destino, Package } from "@land-tour/shared";

// ─── Destinos Mock ────────────────────────────────────────────────────────────
// Datos de ejemplo para Fase 1 MVP (sin base de datos)
export const MOCK_DESTINOS: Destino[] = [
  {
    id: 1,
    pais: "Ecuador",
    ciudad: "Galápagos",
    tagline: "Las Islas Encantadas",
    description:
      "Descubre la biodiversidad única del archipiélago más famoso del mundo, declarado Patrimonio de la Humanidad.",
    image: "/images/destinations/galapagos.jpg",
    highlights: ["Fauna endémica", "Buceo de clase mundial", "Paisajes volcánicos"],
    packageCount: 4,
    color: "from-teal-700/80",
  },
  {
    id: 2,
    pais: "Ecuador",
    ciudad: "Quito",
    tagline: "Centro del Mundo",
    description:
      "La capital más alta del mundo con un Centro Histórico Patrimonio de la Humanidad y una gastronomía inigualable.",
    image: "/images/destinations/quito.jpg",
    highlights: ["Centro histórico", "Mitad del Mundo", "Gastronomía andina"],
    packageCount: 3,
    color: "from-emerald-700/80",
  },
  {
    id: 3,
    pais: "Ecuador",
    ciudad: "Cuenca",
    tagline: "La Atenas de Ecuador",
    description:
      "Ciudad colonial declarada Patrimonio de la Humanidad, famosa por su arquitectura, artesanías y naturaleza.",
    image: "/images/destinations/cuenca.jpg",
    highlights: ["Arquitectura colonial", "Parques naturales", "Artesanías"],
    packageCount: 2,
    color: "from-amber-700/80",
  },
  {
    id: 4,
    pais: "Perú",
    ciudad: "Cusco",
    tagline: "La Ciudad Imperial",
    description:
      "Antigua capital del Imperio Inca, puerta de entrada a Machu Picchu y el Valle Sagrado de los Incas.",
    image: "/images/destinations/cusco.jpg",
    highlights: ["Machu Picchu", "Valle Sagrado", "Cultura inca"],
    packageCount: 5,
    color: "from-orange-700/80",
  },
  {
    id: 5,
    pais: "Colombia",
    ciudad: "Cartagena",
    tagline: "La Ciudad Amurallada",
    description:
      "Joya del Caribe colombiano con su casco histórico amurallado, playas paradisíacas y vibrante cultura.",
    image: "/images/destinations/cartagena.jpg",
    highlights: ["Ciudad amurallada", "Playas del Caribe", "Gastronomía caribeña"],
    packageCount: 3,
    color: "from-rose-700/80",
  },
  {
    id: 6,
    pais: "Argentina",
    ciudad: "Buenos Aires",
    tagline: "La París de América del Sur",
    description:
      "Cosmopolita y apasionada, Buenos Aires combina arquitectura europea con la calidez latinoamericana y el tango.",
    image: "/images/destinations/buenos-aires.jpg",
    highlights: ["Tango", "Gastronomía", "Arquitectura europea"],
    packageCount: 4,
    color: "from-sky-700/80",
  },
];

// ─── Paquetes Mock ────────────────────────────────────────────────────────────
// Datos de ejemplo para Fase 1 MVP (sin base de datos)
export const MOCK_PACKAGES: Package[] = [
  {
    id: "1",
    title: "Galápagos Mágico",
    description:
      "Vive una experiencia única navegando entre las islas del archipiélago, observando fauna irrepetible y paisajes volcánicos de otro mundo.",
    price: 1850,
    image: "/images/packages/galapagos-magic.jpg",
    category: "Naturaleza",
    duration: "8 días / 7 noches",
    nochesBase: 7,
    diasEstancia: 8,
    location: { country: "Ecuador", city: "Galápagos" },
    includes: [
      "Vuelos internos Quito-Galápagos-Quito",
      "Hotel 3 estrellas en Santa Cruz",
      "Tours en lancha a las islas",
      "Guía naturalista certificado",
      "Desayunos incluidos",
    ],
    notIncludes: [
      "Vuelo internacional",
      "Tarjeta de ingreso al PNG ($100)",
      "Almuerzo y cenas",
      "Gastos personales",
    ],
    prices: { sgl: 2100, dbl: 1850, tpl: 1700, quad: 1600 },
    flightIncluded: false,
    transport: "Aéreo + Lancha",
  },
  {
    id: "2",
    title: "Quito Colonial & Mitad del Mundo",
    description:
      "Descubre la historia viva de Quito, su majestuosa arquitectura colonial y para en el punto exacto donde se divide el planeta.",
    price: 620,
    image: "/images/packages/quito-colonial.jpg",
    category: "Cultural",
    duration: "4 días / 3 noches",
    nochesBase: 3,
    diasEstancia: 4,
    location: { country: "Ecuador", city: "Quito" },
    includes: [
      "Hotel 4 estrellas en Quito",
      "City tour Centro Histórico",
      "Visita Mitad del Mundo",
      "Teleférico Quito",
      "Desayunos incluidos",
    ],
    notIncludes: [
      "Vuelo internacional",
      "Almuerzo y cenas",
      "Gastos personales",
    ],
    prices: { sgl: 720, dbl: 620, tpl: 580, quad: 550 },
    flightIncluded: false,
    transport: "Terrestre",
  },
  {
    id: "3",
    title: "Machu Picchu & Cusco Imperial",
    description:
      "Recorre la ciudadela perdida de los incas, el Valle Sagrado y la imperial ciudad del Cusco en un viaje que cambiará tu vida.",
    price: 1350,
    image: "/images/packages/machu-picchu.jpg",
    category: "Aventura",
    duration: "6 días / 5 noches",
    nochesBase: 5,
    diasEstancia: 6,
    location: { country: "Perú", city: "Cusco" },
    includes: [
      "Hotel 3 estrellas en Cusco",
      "Tren a Machu Picchu (ida/vuelta)",
      "Bus a ciudadela",
      "Entrada a Machu Picchu",
      "City tour Cusco",
      "Valle Sagrado",
      "Desayunos incluidos",
    ],
    notIncludes: [
      "Vuelo internacional",
      "Vuelo Lima-Cusco-Lima",
      "Almuerzo y cenas",
      "Gastos personales",
    ],
    prices: { sgl: 1550, dbl: 1350, tpl: 1250, quad: 1180 },
    flightIncluded: false,
    transport: "Tren + Bus",
  },
  {
    id: "4",
    title: "Cartagena de Indias Todo Incluido",
    description:
      "Relájate en el Caribe colombiano con hotel todo incluido, playas de arena blanca y la magia de la ciudad amurallada.",
    price: 980,
    image: "/images/packages/cartagena.jpg",
    category: "Playa",
    duration: "5 días / 4 noches",
    nochesBase: 4,
    diasEstancia: 5,
    location: { country: "Colombia", city: "Cartagena" },
    includes: [
      "Hotel 4 estrellas Todo Incluido",
      "Traslados aeropuerto/hotel",
      "Tour ciudad amurallada",
      "Paseo en bote islas del Rosario",
      "Todas las comidas",
    ],
    notIncludes: [
      "Vuelo internacional",
      "Gastos personales",
      "Excursiones opcionales",
    ],
    prices: { sgl: 1180, dbl: 980, tpl: 900, quad: 860 },
    flightIncluded: false,
    transport: "Terrestre",
  },
  {
    id: "5",
    title: "Buenos Aires & Tango",
    description:
      "Sumérgete en la apasionante cultura porteña: tango, gastronomía gourmet, museos y la arquitectura más europea de Latinoamérica.",
    price: 1150,
    image: "/images/packages/buenos-aires.jpg",
    category: "Cultural",
    duration: "7 días / 6 noches",
    nochesBase: 6,
    diasEstancia: 7,
    location: { country: "Argentina", city: "Buenos Aires" },
    includes: [
      "Hotel 4 estrellas en Palermo",
      "City tour Buenos Aires",
      "Show de Tango con cena",
      "Visita La Boca & San Telmo",
      "Desayunos incluidos",
    ],
    notIncludes: [
      "Vuelo internacional",
      "Almuerzo y cenas adicionales",
      "Gastos personales",
    ],
    prices: { sgl: 1320, dbl: 1150, tpl: 1060, quad: 990 },
    flightIncluded: false,
    transport: "Terrestre",
  },
  {
    id: "6",
    title: "Cuenca y Ruta del Cacao",
    description:
      "Explora la ciudad colonial de Cuenca, el Parque Nacional Cajas y descubre el origen del mejor cacao del mundo en Ecuador.",
    price: 540,
    image: "/images/packages/cuenca.jpg",
    category: "Cultural",
    duration: "4 días / 3 noches",
    nochesBase: 3,
    diasEstancia: 4,
    location: { country: "Ecuador", city: "Cuenca" },
    includes: [
      "Hotel 3 estrellas en Cuenca",
      "City tour Centro Histórico",
      "Visita Parque Nacional Cajas",
      "Tour fábrica de chocolate",
      "Desayunos incluidos",
    ],
    notIncludes: [
      "Vuelo o bus desde Quito",
      "Almuerzo y cenas",
      "Gastos personales",
    ],
    prices: { sgl: 630, dbl: 540, tpl: 490, quad: 460 },
    flightIncluded: false,
    transport: "Terrestre",
  },
];
